import { useState } from 'react'
import {
  AlertTriangle, ArrowRight, CheckCircle2, Cloud, Code2, Droplets, Gauge,
  Menu, Radio, ShieldCheck, Snowflake, Thermometer, Timer, Wifi, X
} from 'lucide-react'

const navigation = [['Overview', '#overview'], ['Architecture', '#architecture'], ['Hardware', '#hardware'], ['Thresholds', '#thresholds']]
const sensors = [
  { Icon: Wifi, name: 'ESP32', role: 'Wi-Fi Microcontroller', description: 'Telemetry engine', color: 'bg-blue-50 text-blue-600' },
  { Icon: Thermometer, name: 'DHT11', role: 'Ambient Air Sensor', description: 'Temperature & humidity', color: 'bg-emerald-50 text-emerald-600' },
  { Icon: Gauge, name: 'DS18B20', role: 'Waterproof Food Probe', description: 'Core food temperature', color: 'bg-amber-50 text-amber-600' },
  { Icon: Cloud, name: 'MQ-135', role: 'Air Quality Sensor', description: 'VOC & ammonia detection', color: 'bg-rose-50 text-rose-600' }
]
const thresholds = [
  ['Air temperature', '1°C – 4°C', '2.5°C', Thermometer],
  ['Food temperature', '0°C – 4°C', '1.8°C', Snowflake],
  ['Humidity', '85% – 95% RH', '89% RH', Droplets],
  ['Gas / VOC', '< 350 ppm', '124 ppm', Cloud]
]

function Brand() {
  return <a href="/" aria-label="ColdGuard home" className="flex items-center gap-2 text-xl font-extrabold tracking-tight text-slate-950"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-600 text-white"><Snowflake size={18} aria-hidden="true" /></span>ColdGuard</a>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <div className="overflow-hidden">
    <a href="#overview" className="sr-only absolute left-4 top-4 z-[60] rounded-md bg-white px-3 py-2 text-sm font-semibold text-blue-700 shadow focus:not-sr-only">Skip to content</a>
    <header className="sticky top-0 z-50 border-b border-slate-100 bg-white/90 backdrop-blur">
      <nav className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8" aria-label="Primary navigation">
        <Brand />
        <div className="hidden items-center gap-7 md:flex">{navigation.map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-slate-600 transition hover:text-blue-600">{label}</a>)}</div>
        <a href="/dashboard" className="hidden items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 sm:flex">Launch Live Dashboard <ArrowRight size={16} aria-hidden="true" /></a>
        <button type="button" onClick={() => setMenuOpen(open => !open)} aria-expanded={menuOpen} aria-controls="mobile-navigation" aria-label="Toggle navigation menu" className="rounded-md p-2 text-slate-700 md:hidden">{menuOpen ? <X aria-hidden="true" /> : <Menu aria-hidden="true" />}</button>
      </nav>
      {menuOpen && <div id="mobile-navigation" className="border-t border-slate-100 bg-white px-5 pb-5 md:hidden"><div className="flex flex-col gap-1 pt-3">{navigation.map(([label, href]) => <a onClick={() => setMenuOpen(false)} key={href} href={href} className="rounded-lg px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">{label}</a>)}<a href="/dashboard" className="mt-2 rounded-lg bg-blue-600 px-3 py-2.5 text-center text-sm font-semibold text-white">Launch Live Dashboard</a></div></div>}
    </header>

    <main id="overview">
      <section className="bg-gradient-to-b from-blue-50/80 via-white to-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-semibold text-blue-700 shadow-sm"><span className="h-2 w-2 rounded-full bg-emerald-500" />IOT COLD STORAGE MONITORING</p><h1 className="text-4xl font-extrabold leading-[1.08] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Precision Cold Chain <span className="text-blue-600">Telemetry</span> &amp; Spoilage Prevention.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Real-time IoT monitoring to eliminate manual logging errors and safeguard perishable goods.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="/dashboard" className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-5 py-3.5 font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700">Launch Live Dashboard <ArrowRight size={18} aria-hidden="true" /></a><a href="#architecture" className="inline-flex items-center justify-center rounded-lg border border-slate-200 bg-white px-5 py-3.5 font-semibold text-slate-700 transition hover:border-blue-200 hover:text-blue-700">View Architecture Specs</a></div><div className="mt-10 flex flex-wrap items-center gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-500" aria-hidden="true" />Continuous monitoring</span><span className="flex items-center gap-2"><Radio size={18} className="text-blue-600" aria-hidden="true" />Live telemetry</span></div></div><TelemetryWidget /></div></section>

      <section className="border-y border-slate-100 bg-slate-50" aria-label="System highlights"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-slate-200 px-5 lg:grid-cols-4 lg:px-8">{[['24/7', 'Continuous capture'], ['< 60 sec', 'Heartbeat monitoring'], ['4', 'Sensor inputs'], ['Instant', 'Threshold alerts']].map(([value, label]) => <div key={label} className="px-5 py-7 text-center"><p className="font-mono text-xl font-semibold text-blue-600">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div></section>

      <section id="architecture" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Why ColdGuard</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">From delayed paperwork to actionable, continuous insight.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">ColdGuard captures the conditions that determine product safety, then turns each reading into a clear operational signal for the team responsible.</p></div><div className="grid gap-4 sm:grid-cols-2"><Compare title="Manual paper logs" points={['Sparse, human-entered checks', 'Errors discovered after spoilage', 'No evidence between rounds']} icon={AlertTriangle} tone="warning" /><Compare title="ColdGuard telemetry" points={['Automated, timestamped readings', 'Instant exception notification', 'A complete environmental record']} icon={CheckCircle2} tone="healthy" /></div></div></section>

      <section id="hardware" className="bg-slate-50 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Sensor suite</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Designed for every critical condition.</h2><p className="mt-4 leading-7 text-slate-600">A focused sensor stack provides a dependable picture of storage health, from the surrounding air to the food itself.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{sensors.map(({ Icon, name, role, description, color }) => <article key={name} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><div className={`grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon size={22} aria-hidden="true" /></div><h3 className="mt-6 text-lg font-bold text-slate-900">{name}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{role}</p><p className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-600">{description}</p></article>)}</div></div></section>

      <section id="thresholds" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Academic safe operating targets</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Safe ranges, made visible.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">These evaluation targets are separate from the live prototype dashboard’s configurable thresholds.</p></div><div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-medium text-amber-800"><Timer size={18} aria-hidden="true" />Offline alert after 60 seconds of lost heartbeat.</div></div><div className="mt-9 overflow-hidden rounded-2xl border border-slate-200"><div className="grid grid-cols-[1.25fr_1fr_.85fr] bg-slate-900 px-5 py-4 text-xs font-bold uppercase tracking-wider text-slate-300 sm:px-7"><span>Measurement</span><span>Safe range</span><span>Illustrative sample</span></div>{thresholds.map(([label, range, current, Icon]) => <div key={label} className="grid grid-cols-[1.25fr_1fr_.85fr] items-center border-t border-slate-100 bg-white px-5 py-5 sm:px-7"><div className="flex items-center gap-3"><span className="hidden rounded-lg bg-blue-50 p-2 text-blue-600 sm:block"><Icon size={18} aria-hidden="true" /></span><span className="font-semibold text-slate-800">{label}</span></div><span className="font-mono text-sm text-slate-600">{range}</span><span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 font-mono text-xs font-semibold text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />{current}</span></div>)}</div></section>
    </main>
    <Footer />
  </div>
}

function TelemetryWidget() { return <aside aria-label="Illustrative cold room telemetry" className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 rounded-[2rem] bg-blue-200/40 blur-3xl" /><div className="relative rounded-3xl border border-slate-200 bg-white p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-800">Cold Room 01</p><p className="mt-1 font-mono text-xs text-slate-400">ILLUSTRATIVE · CG-ESP32-001</p></div><div className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700"><span className="relative flex h-2 w-2"><span className="absolute inline-flex h-full w-full animate-pulseRing rounded-full bg-emerald-400" /><span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" /></span>LIVE SAMPLE</div></div><div className="my-6 grid place-items-center"><div className="grid h-52 w-52 place-items-center rounded-full border-[13px] border-blue-100 bg-gradient-to-b from-blue-50 to-white shadow-inner"><div className="text-center"><Thermometer className="mx-auto mb-2 text-blue-600" size={24} aria-hidden="true" /><p className="font-mono text-5xl font-semibold tracking-tight text-slate-900">2.5<span className="text-2xl">°C</span></p><p className="mt-2 text-sm font-semibold text-emerald-600">● NORMAL STATUS</p></div></div></div><div className="grid grid-cols-3 gap-3 border-t border-slate-100 pt-5">{[['Humidity', '89% RH'], ['VOC Gas', '124 ppm'], ['Updated', 'Now']].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-[11px] font-medium text-slate-500">{label}</p><p className="mt-1 font-mono text-xs font-semibold text-slate-800">{value}</p></div>)}</div></div></aside> }

function Compare({ title, points, icon: Icon, tone }) { const healthy = tone === 'healthy'; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className={`flex items-center gap-2 font-bold ${healthy ? 'text-emerald-600' : 'text-amber-600'}`}><Icon size={20} aria-hidden="true" />{title}</h3><ul className="mt-4 space-y-3">{points.map(point => <li key={point} className="flex gap-2 text-sm leading-5 text-slate-600"><span className={`mt-1 h-1.5 w-1.5 shrink-0 rounded-full ${healthy ? 'bg-emerald-500' : 'bg-amber-500'}`} />{point}</li>)}</ul></article> }

function Footer() { return <footer className="border-t border-slate-200 bg-slate-950 text-slate-400"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-9 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><div className="flex items-center gap-2 text-lg font-bold text-white"><Snowflake size={18} className="text-blue-400" aria-hidden="true" />ColdGuard</div><p className="mt-2 text-sm">ColdGuard - Engineering Project Prototype</p></div><div className="flex gap-5 text-sm"><a href="https://github.com/your-organization/coldguard" title="Placeholder GitHub URL" className="inline-flex items-center gap-1.5 transition hover:text-white"><Code2 size={16} aria-hidden="true" />GitHub Repository</a><a href="https://example.edu/coldguard-documentation" title="Placeholder documentation URL" className="transition hover:text-white">Documentation</a></div></div></footer> }

export default App
